name: Deploy to EC2

on:
  push:
    branches:
      - prod

jobs:
  deploy:
    name: Push to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: executing remote ssh commands
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: 13.63.130.4
          username: ubuntu
          key: ${{ secrets.PRIVATE_SSH_KEY_PROD }}
          port: 22
          script: |
            export PATH=$PATH:/usr/bin:/usr/local/bin
            cd /home/ubuntu/practice_cicd
            git pull origin prod
            npm install
            npm run build
            pm2 restart practice-cicd || pm2 start npm --name "practice-cicd" -- start